return {
  "rebelot/kanagawa.nvim",
  lazy = true,
  opts = {
    dimInactive = true, -- dim inactive window `:h hl-NormalNC`
    -- Remove gutter background
    colors = {
      theme = {
        all = {
          ui = {
            bg_gutter = "none",
          },
        },
      },
    },
    overrides = function(colors)
      local theme = colors.theme
      return {
        -- Transparent background
        NormalFloat = { bg = "none" },
        FloatBorder = { bg = "none" },
        FloatTitle = { bg = "none" },

        NormalDark = { fg = theme.ui.fg_dim, bg = theme.ui.bg_m3 },
        LazyNormal = { bg = theme.ui.bg_m3, fg = theme.ui.fg_dim },
        MasonNormal = { bg = theme.ui.bg_m3, fg = theme.ui.fg_dim },

        -- Credit to https://github.com/rebelot/kanagawa.nvim/pull/268
        -- SnacksDashboard
        SnacksDashboardHeader = { fg = theme.vcs.removed },
        SnacksDashboardFooter = { fg = theme.syn.comment },
        SnacksDashboardDesc = { fg = theme.syn.identifier },
        SnacksDashboardIcon = { fg = theme.ui.special },
        SnacksDashboardKey = { fg = theme.syn.special1 },
        SnacksDashboardSpecial = { fg = theme.syn.comment },
        SnacksDashboardDir = { fg = theme.syn.identifier },
        -- SnacksNotifier
        SnacksNotifierBorderError = { link = "DiagnosticError" },
        SnacksNotifierBorderWarn = { link = "DiagnosticWarn" },
        SnacksNotifierBorderInfo = { link = "DiagnosticInfo" },
        SnacksNotifierBorderDebug = { link = "Debug" },
        SnacksNotifierBorderTrace = { link = "Comment" },
        SnacksNotifierIconError = { link = "DiagnosticError" },
        SnacksNotifierIconWarn = { link = "DiagnosticWarn" },
        SnacksNotifierIconInfo = { link = "DiagnosticInfo" },
        SnacksNotifierIconDebug = { link = "Debug" },
        SnacksNotifierIconTrace = { link = "Comment" },
        SnacksNotifierTitleError = { link = "DiagnosticError" },
        SnacksNotifierTitleWarn = { link = "DiagnosticWarn" },
        SnacksNotifierTitleInfo = { link = "DiagnosticInfo" },
        SnacksNotifierTitleDebug = { link = "Debug" },
        SnacksNotifierTitleTrace = { link = "Comment" },
        SnacksNotifierError = { link = "DiagnosticError" },
        SnacksNotifierWarn = { link = "DiagnosticWarn" },
        SnacksNotifierInfo = { link = "DiagnosticInfo" },
        SnacksNotifierDebug = { link = "Debug" },
        SnacksNotifierTrace = { link = "Comment" },
        -- SnacksProfiler
        SnacksProfilerIconInfo = { bg = theme.ui.bg_search, fg = theme.syn.fun },
        SnacksProfilerBadgeInfo = { bg = theme.ui.bg_visual, fg = theme.syn.fun },
        SnacksScratchKey = { link = "SnacksProfilerIconInfo" },
        SnacksScratchDesc = { link = "SnacksProfilerBadgeInfo" },
        SnacksProfilerIconTrace = { bg = theme.syn.fun, fg = theme.ui.float.fg_border },
        SnacksProfilerBadgeTrace = { bg = theme.syn.fun, fg = theme.ui.float.fg_border },
        SnacksIndent = { fg = theme.ui.bg_p2, nocombine = true },
        SnacksIndentScope = { fg = theme.ui.pmenu.bg, nocombine = true },
        SnacksZenIcon = { fg = theme.syn.statement },
        SnacksInputIcon = { fg = theme.ui.pmenu.bg },
        SnacksInputBorder = { fg = theme.syn.identifier },
        SnacksInputTitle = { fg = theme.syn.identifier },
        -- SnacksPicker
        SnacksPickerInputBorder = { fg = theme.syn.constant },
        SnacksPickerInputTitle = { fg = theme.syn.constant },
        SnacksPickerBoxTitle = { fg = theme.syn.constant },
        SnacksPickerSelected = { fg = theme.syn.number },
        SnacksPickerToggle = { link = "SnacksProfilerBadgeInfo" },
        SnacksPickerPickWinCurrent = { fg = theme.ui.fg, bg = theme.syn.number, bold = true },
        SnacksPickerPickWin = { fg = theme.ui.fg, bg = theme.ui.bg_search, bold = true },

        -- mini.nvim
        MiniDiffSignAdd = { fg = theme.vcs.added },
        MiniDiffSignChange = { fg = theme.vcs.changed },
        MiniDiffSignDelete = { fg = theme.vcs.removed },
        MiniDiffOverAdd = { fg = theme.vcs.added, bg = theme.ui.bg_visual },
        MiniDiffOverChange = { fg = theme.vcs.changed, bg = theme.ui.bg_visual },
        MiniDiffOverChangeBuf = { fg = theme.vcs.changed, bg = theme.ui.bg_visual },
        MiniDiffOverContext = { bg = theme.ui.bg_p2 },
        MiniDiffOverContextBuf = { bg = theme.ui.bg_p2 },
        MiniDiffOverDelete = { fg = theme.vcs.removed, bg = theme.ui.bg_visual },

        MiniIconsAzure = { fg = theme.syn.special1 },
        MiniIconsBlue = { fg = theme.syn.keyword },
        MiniIconsCyan = { fg = theme.syn.string },
        MiniIconsGreen = { fg = theme.syn.fun },
        MiniIconsGrey = { fg = theme.ui.fg_dim },
        MiniIconsOrange = { fg = theme.syn.constant },
        MiniIconsPurple = { fg = theme.syn.special1 },
        MiniIconsRed = { fg = theme.vcs.removed },
        MiniIconsYellow = { fg = theme.syn.operator },

        MiniHipatternsFixme = { fg = theme.ui.bg_m3, bg = theme.vcs.removed, bold = true },
        MiniHipatternsHack = { fg = theme.ui.bg_m3, bg = theme.syn.special1, bold = true },
        MiniHipatternsNote = { fg = theme.ui.bg_m3, bg = theme.syn.keyword, bold = true },
        MiniHipatternsTodo = { fg = theme.ui.bg_m3, bg = theme.syn.fun, bold = true },

        MiniPickNormal = { fg = theme.ui.fg, bg = theme.ui.bg_m3 },
        MiniPickBorder = { fg = theme.ui.float.fg_border, bg = theme.ui.bg_m3 },
        MiniPickBorderBusy = { fg = theme.syn.special1, bg = theme.ui.bg_m3 },
        MiniPickBorderText = { fg = theme.ui.special, bg = theme.ui.bg_m3 },
        MiniPickHeader = { fg = theme.syn.statement },
        MiniPickCursor = { link = "Cursor" },
        MiniPickMatchCurrent = { fg = theme.ui.fg, bg = theme.ui.bg_visual, bold = true },
        MiniPickMatchMarked = { fg = theme.syn.special1, bg = theme.ui.bg_visual, bold = true },
        MiniPickMatchRanges = { fg = theme.syn.number, bold = true },
        MiniPickPrompt = { fg = theme.syn.fun, bold = true },
        MiniPickPromptCaret = { fg = theme.syn.constant, bg = theme.ui.bg_m3, bold = true },
        MiniPickPromptPrefix = { fg = theme.syn.statement, bg = theme.ui.bg_m3 },
        MiniPickPromptSymbol = { fg = theme.syn.constant },
        MiniPickIconDirectory = { fg = theme.syn.identifier },
        MiniPickIconFile = { fg = theme.ui.fg_dim },
        MiniPickPreviewLine = { bg = theme.ui.bg_p2 },
        MiniPickPreviewRegion = { bg = theme.ui.bg_visual },

        MiniStarterCurrent = { bg = theme.ui.bg_visual },
        MiniStarterFooter = { fg = theme.syn.comment },
        MiniStarterHeader = { fg = theme.syn.special1 },
        MiniStarterInactive = { fg = theme.ui.fg_dim },
        MiniStarterItem = { fg = theme.ui.fg },
        MiniStarterItemBullet = { fg = theme.syn.constant },
        MiniStarterItemPrefix = { fg = theme.syn.identifier },
        MiniStarterQuery = { fg = theme.syn.keyword, bold = true },
        MiniStarterSection = { fg = theme.syn.statement, bold = true },

        MiniStatuslineDevinfo = { fg = theme.ui.fg_dim, bg = theme.ui.bg_m3 },
        MiniStatuslineFileinfo = { fg = theme.ui.fg_dim, bg = theme.ui.bg_m3 },
        MiniStatuslineFilename = { fg = theme.ui.fg, bg = theme.ui.bg_m3, bold = true },
        MiniStatuslineInactive = { fg = theme.ui.fg_dim, bg = theme.ui.bg_p2 },
        MiniStatuslineModeNormal = { fg = theme.ui.bg_m3, bg = theme.syn.fun, bold = true },
        MiniStatuslineModeInsert = { fg = theme.ui.bg_m3, bg = theme.syn.string, bold = true },
        MiniStatuslineModeVisual = { fg = theme.ui.bg_m3, bg = theme.syn.keyword, bold = true },
        MiniStatuslineModeReplace = { fg = theme.ui.bg_m3, bg = theme.vcs.removed, bold = true },
        MiniStatuslineModeCommand = { fg = theme.ui.bg_m3, bg = theme.syn.operator, bold = true },
        MiniStatuslineModeOther = { fg = theme.ui.bg_m3, bg = theme.syn.special1, bold = true },

        MiniTablineCurrent = { fg = theme.ui.fg, bg = theme.ui.bg_p2, bold = true },
        MiniTablineFill = { bg = theme.ui.bg_m3 },
        MiniTablineHidden = { fg = theme.ui.fg_dim, bg = theme.ui.bg_p1 },
        MiniTablineModifiedCurrent = { fg = theme.syn.special1, bg = theme.ui.bg_p2 },
        MiniTablineModifiedHidden = { fg = theme.syn.special1, bg = theme.ui.bg_p1 },
        MiniTablineModifiedVisible = { fg = theme.syn.special1, bg = theme.ui.bg_p2 },
        MiniTablineTabpagesection = { fg = theme.syn.special1, bg = theme.ui.bg_p1, bold = true },
        MiniTablineTrunc = { fg = theme.ui.fg_dim, bg = theme.ui.bg_m3 },
        MiniTablineVisible = { fg = theme.ui.fg_dim, bg = theme.ui.bg_p2 },
      }
    end,
  },
}
